using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class EnableGiantModel

{
    [RealtimeProperty(1, true, true)]
    bool _giantOn;

}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class EnableGiantModel : RealtimeModel {
    public bool giantOn {
        get {
            return _giantOnProperty.value;
        }
        set {
            if (_giantOnProperty.value == value) return;
            _giantOnProperty.value = value;
            InvalidateReliableLength();
            FireGiantOnDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(EnableGiantModel model, T value);
    public event PropertyChangedHandler<bool> giantOnDidChange;
    
    public enum PropertyID : uint {
        GiantOn = 1,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _giantOnProperty;
    
    #endregion
    
    public EnableGiantModel() : base(null) {
        _giantOnProperty = new ReliableProperty<bool>(1, _giantOn);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _giantOnProperty.UnsubscribeCallback();
    }
    
    private void FireGiantOnDidChange(bool value) {
        try {
            giantOnDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _giantOnProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _giantOnProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.GiantOn: {
                    changed = _giantOnProperty.Read(stream, context);
                    if (changed) FireGiantOnDidChange(giantOn);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _giantOn = giantOn;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
